---
- name: Install Apt packages
  hosts: localhost
  become: yes
  tasks:
    - apt: name={{ item }} update_cache=yes
      with_items:
        - vim
        - tilix
      tags: utilities

    - apt: name={{ item }} update_cache=yes
      with_items:
        - git
        - subversion
      tags: vcs

    - name: Install System Inspection Tools
      apt: name={{ item }}
      with_items:
        - nmap
        - tcpdump
        - iftop
        - iotop
        - htop
        - valgrind
        - httpie
      tags: inspection

    - name: Install VM Tools
      apt: name={{ item }}
      with_items:
        - vagrant
        - virtualbox
      tags: vm

- name: Setup environment
  hosts: localhost
  roles:
    - dots
    - autoenv
    - bash-git-prompt
  tags: env
