---
- name: Install docker-ce
  hosts: localhost
  become: yes
  tasks:
    - command: /usr/bin/env docker
      register: docker_exists
      ignore_errors: yes
      changed_when: false

    - uri:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
      when: docker_exists.rc != 0

    - script: /tmp/get-docker.sh
      when: docker_exists.rc != 0

    - group:
        name: docker
        state: present

    - user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes
