---
- name: Install Apt packages
  hosts: localhost
  become: yes
  tasks:
    - apt: name={{ item }} update_cache=yes
      with_items:
        - dconf-editor
        - vim
        - tilix
      tags: apt, utilities

    - apt: name={{ item }} update_cache=yes
      with_items:
        - git
        - subversion
      tags: apt, vcs

    - name: Install System Inspection Tools
      apt: name={{ item }}
      with_items:
        - nmap
        - tcpdump
        - iftop
        - iotop
        - htop
        - valgrind
        - httpie
        - net-tools
        - jq
      tags: apt, inspection

    - name: Install VM Tools
      apt: name={{ item }}
      with_items:
        - vagrant
        - virtualbox
      tags: apt, vm

- name: Setup environment
  hosts: localhost
  roles:
    - dots
    - autoenv
    - bash-git-prompt
  tags: env
  vars_files:
    - ../config.yml
