---
- name: Install Apt packages
  hosts: localhost
  become: yes
  tasks:
    - apt:
        name: "{{ item }}"
      with_items:
        - vim
        - terminator
        - curl
        - jq
      tags: apt, utilities

    - apt:
        name: "{{ item }}"
      with_items:
        - git
        - subversion
      tags: apt, vcs

    - name: Install System Inspection Tools
      apt:
        name: "{{ item }}"
      with_items:
        - nmap
        - tcpdump
        - iftop
        - iotop
        - htop
        - valgrind
        - httpie
        - net-tools
      tags: apt, inspection

    - name: Install VM Tools
      apt:
        name: "{{ item }}"
      with_items:
        - vagrant
        - virtualbox
      tags: apt, vm

- name: Setup environment
  hosts: localhost
  roles:
    - dots
    - autoenv
    - bash-git-prompt
  tags: env
  vars_files:
    - ../config.yml
  tasks:
    - blockinfile:
        path: "{{ home_dir }}/.bashrc"
        marker: "# {mark} ANSIBLE ROLE: KDE BLUR"
        insertbefore: "^# ~/.bashrc"
        block: |
          if [[ $(ps --no-header -p $PPID -o comm) =~ terminator ]]; then
            for wid in $(xdotool search --pid $PPID); do
              xprop \
                -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c \
                -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 \
                -id $wid
            done
          fi
