---
- name: Install Golang Development Environment
  hosts: localhost
  become: yes
  tasks:
    - name: Install Packages
      apt:
        name: "{{ item }}"
      with_items:
        - golang
        - golang-golang-x-tools

