---
- name: Install Node.js Development Environment
  hosts: localhost
  become: yes
  tasks:
    - name: Install NodeJS and NPM
      apt: name={{ item }} update_cache=yes
      with_items:
        - nodejs
        - npm

    - name: Install Node.js Tools
      npm: name={{ item }} global=yes
      with_items:
        - grunt
        - gulp
        - bower
        - http-server
        - typescript
        - jshint
        - jasmine
        - webpack
        - mocha
        - create-react-app
