---
- name: Install python development packages
  hosts: localhost
  become: yes
  tasks:
  - name: Install Python build dependencies
    tags: build-deps
    apt:
      name:
      - python-dev
      - python-pip
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - libffi-dev
      - build-essential
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - liblzma-dev
      - python-openssl

- name: Install pyenv pyenv-virtualenv
  hosts: localhost
  roles:
  - pyenv
  - pyenv/virtualenv
