---
- name: setup sublime-text settings
  hosts: localhost
  tasks:
    - apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present
      become: yes

    - apt:
        name: apt-transport-https
      become: yes

    - copy:
        content: "deb https://download.sublimetext.com/ apt/stable/"
        dest: /etc/apt/sources.list.d/sublime-text.list
      become: yes

    - apt:
        name: sublime-text
        update_cache: yes
      become: yes

    - file:
        path: "{{ home_dir }}/.config/sublime-text-3/Packages/User"
        state: directory

    - copy:
        src: ../editors/sublime-settings/{{ item }}
        dest: "{{ home_dir }}/.config/sublime-text-3/Packages/User/{{ item }}"
      with_items:
        - Preferences.sublime-settings
        - Package Control.sublime-settings
        - Terminal.sublime-settings
      tags:
        - config
