---
- name: get pyenv from git repository
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ home_dir }}/.pyenv"

- name: ensure .bashrc has pyenv activate routine
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} ANSIBLE ROLE: PYENV"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
      fi
