---
- name: get bash-git-prompt from git repository
  git:
    repo: https://github.com/magicmonty/bash-git-prompt.git
    dest: "{{ home_dir }}/.bash-git-prompt"

- name: copy my theme
  copy:
    src: Jwl.bgptheme
    dest: "{{ home_dir }}/.bash-git-prompt/themes/Jwl.bgptheme"

- name: activate bash-git-prompt
  blockinfile:
    path: "{{ home_dir }}/.bashrc"
    marker: "# {mark} ANSIBLE ROLE: BASH-GIT-PROMPT"
    block: |
      GIT_PROMPT_ONLY_IN_REPO=0
      GIT_PROMPT_THEME=Jwl
      GIT_PROMPT_LEADING_SPACE=0
      source ~/.bash-git-prompt/gitprompt.sh
